### ISSUE TITLE
hi mr ziko 

### ISSUE THREAD

**Issue by morafbi** [ziko-ZR1/Epg-plugin#22]
hi mr ziko i have kali-Linux try to open your Epg-plugin in my kali cant complete install this plugin for enigma only or have setup it in kali please i wait your answer

**Comment by ziko-ZR1** [comment]
This Plugin is only desired for Linux Set-top Boxes .

But try with this file unzip and replace interfaces.py , online update is not supported you have to update the plugin manually

[interfaces.zip](https://github.com/ziko-ZR1/Epg-plugin/files/5584528/interfaces.zip)
