### ISSUE TITLE
Plugin can not be removed

### ISSUE THREAD

**Issue by ozone1864** [ziko-ZR1/Epg-plugin#27]
Dear Mr. Ziko,
Something happened on my Zgemma H9S receiver and all epg downloaded from your plugin 
it says events imported but nothing on receiver.
I want to remove the plugin and reinstall again but its not uninstalling.
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/Epg_Plugin

the above command not working

**Comment by fairbird** [comment]
The plugin name was changed from few weeks ...
It is EPGGrabber not Epg_Plugin ..
So the correct command is 

> rm -rf /usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber
