### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by persianpros** [ziko-ZR1/Epg-plugin#84]
Take a look at https://github.com/persianpros/Epg-plugin/commit/0bcfacf7e85f65cd44bbfbeb35e42ee28a37af49

Gives you the idea to do what ;)

**Comment by fairbird** [comment]
https://github.com/ziko-ZR1/Epg-plugin/commit/2de6691d186b17c5dd67d38f1ebd7dcdfa00d482

**Comment by persianpros** [comment]
What you merged was PEP8, I've done python 3 in another branch: https://github.com/persianpros/Epg-plugin/commit/0bcfacf7e85f65cd44bbfbeb35e42ee28a37af49

@ziko-ZR1

**Comment by fairbird** [comment]
Thank you .. I have pushed it to branch
https://github.com/ziko-ZR1/Epg-plugin/commit/501c09f72c76313e0aabb29c78710745da1dbf11

**Comment by persianpros** [comment]
Did you test it on a py2 image? that was py3 code...

**Comment by fairbird** [comment]
Yes I know for PY3 .. like that I did not release new version yat ... I will test it first ...
